[package]
name = "dmrparse"
version = "0.1.0"
authors = ["danielbasedow <daniel.basedow@gmail.com>"]

[profile.release]
debug = false

[dependencies]
flate2 = "1.0"
quick-xml = "0.12"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
